//! Generate the README evidence table from the manifest.
//!
//! The README contains a block delimited by [`BEGIN`] / [`END`] markers. The
//! gate's doc-tamper lint re-renders this block and rejects any hand-edit, so
//! the published claims can never drift from the manifest the harness runs.

use crate::manifest::Manifest;

/// Opening marker of the generated block.
pub const BEGIN: &str = "<!-- ASTREAM:EVIDENCE:BEGIN -->";
/// Closing marker of the generated block.
pub const END: &str = "<!-- ASTREAM:EVIDENCE:END -->";

/// Make `s` safe inside one Markdown table cell: a `|` would end the cell, and a
/// line break would end the row.
fn escape(s: &str) -> String {
    s.replace('|', "\\|")
        .replace("\r\n", " ")
        .replace(['\n', '\r'], " ")
}

/// Render the full evidence block (markers included) from the manifest.
///
/// A platform-gated claim is annotated in its "Verified by" cell: the table
/// promises "a command anyone can re-run", and a reader on another OS cannot —
/// `run` skips it there, so the row must say so rather than look like every
/// other row.
pub fn render_block(m: &Manifest) -> String {
    let mut s = String::new();
    s.push_str(BEGIN);
    s.push('\n');
    s.push_str("<!-- generated by `astream-evidence render --write`; do not hand-edit -->\n\n");
    s.push_str(&format!(
        "Every claim below is backed by a command anyone can re-run. Project: `{}`.\n\n",
        m.meta.project
    ));
    s.push_str("| Claim ID | Statement | Verified by |\n");
    s.push_str("|---|---|---|\n");
    for c in &m.claim {
        let platform_note = match &c.platform {
            Some(p) => format!(" (re-run on {} only; skipped elsewhere)", escape(p)),
            None => String::new(),
        };
        s.push_str(&format!(
            "| `{}` | {} | `{}`{} |\n",
            escape(&c.id),
            escape(&c.text),
            escape(&c.command),
            platform_note
        ));
    }
    s.push_str(END);
    s
}

/// Replace the block between the markers (inclusive) in `readme`.
pub fn splice(readme: &str, block: &str) -> Result<String, String> {
    let b = readme
        .find(BEGIN)
        .ok_or("README is missing the BEGIN marker")?;
    let e = readme.find(END).ok_or("README is missing the END marker")?;
    if e < b {
        return Err("README markers are out of order".to_string());
    }
    if readme[b + BEGIN.len()..].contains(BEGIN) || readme[e + END.len()..].contains(END) {
        return Err(
            "README has duplicate evidence markers; remove the extra block by hand".to_string(),
        );
    }
    let e_end = e + END.len();
    let mut out = String::with_capacity(readme.len());
    out.push_str(&readme[..b]);
    out.push_str(block);
    out.push_str(&readme[e_end..]);
    Ok(out)
}

/// Extract the current block (inclusive) from `readme`, if present.
///
/// Returns `None` if a marker is missing, out of order, or **duplicated** —
/// duplicate markers are ambiguous and would let a second hand-edited block
/// escape the doc-tamper comparison (which only inspects the first region), so
/// they are rejected outright. A generated tree has exactly one block.
pub fn extract(readme: &str) -> Option<String> {
    let b = readme.find(BEGIN)?;
    let e = readme.find(END)?;
    if e < b {
        return None;
    }
    if readme[b + BEGIN.len()..].contains(BEGIN) {
        return None;
    }
    if readme[e + END.len()..].contains(END) {
        return None;
    }
    let e_end = e + END.len();
    Some(readme[b..e_end].to_string())
}

#[cfg(test)]
mod tests {
    use super::{extract, render_block, splice, BEGIN, END};
    use crate::manifest::Manifest;

    fn block(inner: &str) -> String {
        format!("{BEGIN}\n{inner}\n{END}")
    }

    #[test]
    fn extract_rejects_duplicate_blocks() {
        let single = format!("prefix\n{}\nsuffix", block("real rows"));
        let got = extract(&single).expect("a single block extracts");
        assert!(got.contains("real rows"));

        let doubled = format!(
            "prefix\n{}\nmiddle\n{}\nsuffix",
            block("real rows"),
            block("fabricated rows")
        );
        assert_eq!(extract(&doubled), None);
    }

    #[test]
    fn splice_rejects_duplicate_blocks() {
        let doubled = format!("{}\n{}", block("a"), block("b"));
        assert!(splice(&doubled, &block("new")).is_err());

        let single = format!("head {} tail", block("a"));
        let spliced = splice(&single, &block("new")).expect("a single block splices");
        assert!(spliced.contains("new"));
    }

    #[test]
    fn platform_gated_rows_are_annotated() {
        let text = "[meta]\nproject = \"p\"\n\n[[claim]]\nid = \"everywhere\"\nkind = \"test\"\ntext = \"t\"\ncommand = \"cargo test --locked\"\n\n[[claim]]\nid = \"linux.only\"\nkind = \"test\"\ntext = \"t\"\ncommand = \"cargo test --locked --test x\"\nplatform = \"linux\"\n";
        let m = Manifest::parse(text, "mem").expect("parses");
        let rendered = render_block(&m);
        assert!(
            rendered.contains("| `linux.only` | t | `cargo test --locked --test x` (re-run on linux only; skipped elsewhere) |"),
            "{rendered}"
        );
        assert!(
            rendered.contains("| `everywhere` | t | `cargo test --locked` |"),
            "{rendered}"
        );
    }

    #[test]
    fn a_line_break_in_a_claim_stays_inside_its_table_row() {
        // A Markdown table row is one line: a newline in the text (a TOML `\n`
        // escape) would end the row and spill the rest out of the table.
        let text = "[meta]\nproject = \"p\"\n\n[[claim]]\nid = \"nl\"\nkind = \"test\"\ntext = \"first\\nsecond\\r\\nthird\"\ncommand = \"cargo test --locked\"\n";
        let m = Manifest::parse(text, "mem").expect("parses");
        let rendered = render_block(&m);
        assert!(
            rendered.contains("| `nl` | first second third | `cargo test --locked` |"),
            "{rendered}"
        );
    }
}
