#!/usr/bin/env bash
# Cross-system Pareto comparison: astream-broker vs Redis at EQUAL conditions —
# same host, same transport (Unix socket), same durability (one fsync per
# operation), same workload (N single, sequential, durable appends of a 64-byte
# payload). Writes a disclosed-hardware artifact to evidence/bench/broker-vs-redis.md.
#
# This is the doctrine's "never worse at equal durability" claim made real: it is an
# ATTACHED ARTIFACT (numbers are machine-specific), not a green CI claim. Re-run it
# anywhere to regenerate. Requires redis-server + redis-benchmark on PATH.
set -euo pipefail
cd "$(dirname "$0")/.."

N="${BENCH_N:-500}"
OUT="evidence/bench/broker-vs-redis.md"
mkdir -p "$(dirname "$OUT")"
DIR="$(mktemp -d)"
SOCK="$DIR/redis.sock"
RPID=""
# Installed before anything else can fail, so neither Redis nor the temp dir
# outlives the run.
cleanup() {
  if [ -n "$RPID" ]; then
    kill "$RPID" 2>/dev/null || true
    wait "$RPID" 2>/dev/null || true
  fi
  rm -rf "$DIR"
}
trap cleanup EXIT

# Redis: AOF on, fsync on EVERY write (matches astream's Strict fsync-per-message),
# RDB off, over a Unix socket — the same transport + durability as astream-broker.
redis-server --unixsocket "$SOCK" --port 0 --appendonly yes --appendfsync always \
  --save '' --dir "$DIR" >/dev/null 2>&1 &
RPID=$!
# Wait (bounded, ~10 s) until Redis answers on the socket. A server that never
# comes up ends the run here instead of being "measured" as nothing.
ready=0
for _ in $(seq 1 200); do
  if redis-cli -s "$SOCK" ping >/dev/null 2>&1; then ready=1; break; fi
  sleep 0.05
done
if [ "$ready" -ne 1 ]; then
  echo "bench-vs-redis: redis-server never answered on $SOCK" >&2
  exit 1
fi

# redis-benchmark prints carriage-return progress lines; the final summary is
# "RPUSH: <rps> requests per second, ...". Split CRs to lines, take the summary.
# Neither tool's stderr is discarded: a failure must say why, not end silently.
REDIS=$(redis-benchmark -s "$SOCK" -n "$N" -c 1 -t rpush -d 64 -q \
  | tr '\r' '\n' | sed -n 's/^RPUSH: \([0-9.]*\) requests per second.*/\1/p' | head -1)

ASTREAM=$(BENCH_N="$N" cargo run --quiet --release --locked -p astream-broker --example broker_microbench \
  | sed -n 's/^METRIC broker_publish_ops_per_sec \([0-9]*\).*/\1/p' | head -1)

# Never overwrite the committed artifact with a result that was not measured.
if [ -z "$REDIS" ] || [ -z "$ASTREAM" ]; then
  echo "bench-vs-redis: no result parsed (astream='$ASTREAM' redis='$REDIS'); $OUT left unchanged" >&2
  exit 1
fi

# The CPU model: macOS names it via sysctl, Linux in /proc/cpuinfo; the
# architecture is the fallback, not the answer.
HW_CPU="$(sysctl -n machdep.cpu.brand_string 2>/dev/null \
  || awk -F': *' '/^model name/ { print $2; exit }' /proc/cpuinfo 2>/dev/null || true)"
HW_CPU="${HW_CPU:-$(uname -m)}"
HW_OS="$(uname -s) $(uname -r)"
HW_PROD="$( (sw_vers -productName && sw_vers -productVersion) 2>/dev/null | paste -sd' ' - || true)"

cat > "$OUT" <<EOF
# astream-broker vs Redis — equal-durability throughput

Generated by \`scripts/bench-vs-redis.sh\` (re-runnable). This is an **attached
comparison artifact**, not a green CI claim: the numbers are machine-specific, so
the doctrine's Pareto rule ships the comparison with disclosed hardware + matched
conditions rather than as a hard assertion.

## Disclosed hardware
- CPU: ${HW_CPU}
- OS: ${HW_OS} ${HW_PROD}

## Matched conditions (the honest part)
- Transport: **Unix domain socket** for both (no TCP/loopback skew).
- Durability: **one fsync per operation** for both — astream Strict (fsync per
  publish, ack only after fsync); Redis \`appendonly yes\` + \`appendfsync always\`,
  RDB disabled.
- Workload: **${N}** single, sequential (one connection), durable appends of a
  64-byte payload. astream: PUBLISH awaiting ack. Redis: RPUSH awaiting reply.

## Result (ops/sec, higher is better)
| System | Durable append throughput |
|---|---|
| astream-broker | ${ASTREAM} |
| Redis (AOF appendfsync always) | ${REDIS} |

Both are fsync-bound at this durability, so throughput is dominated by the host's
fsync latency and the two land in the same order of magnitude — astream meets the
"never worse at equal durability" bar here while ALSO offering replay, counterfactual
fork-delivery, and exactly-once read-process-write, which Redis does not. The faster,
less-durable tiers (Replicated/Relaxed, batched fsync) are a separate track; this
artifact deliberately compares the STRICTEST setting where the durability is equal
and cannot be hidden.
EOF

echo "astream=${ASTREAM} ops/s  redis=${REDIS} ops/s  (N=$N, UDS, fsync/op)"
echo "wrote $OUT"
